sno=int(input("ENTER ROLL NO:"))
name=input("ENTER NAME:")
gender=input("ENTER GENDER:")
group=input("ENTER GROUP:")
address=input("ENTER ADDRESS:")
phno=int(input("ENTER PHONE NUMBER:"))
print(gender)
print(name)
print(group)
print(address)
print(phno)
