a=int(input("Enter a value:"))
b=int(input("Enter b value:"))
print("PERFORMING ALL ARITHMETIC OPERATIONS")
print("ADDITION:",a+b)
print("SUBTRACTION:",a-b)
print("MULTIPLICATION:",a*b)
print("DIVISION:",a/b)
print("MODULUS:",a%b)
print("FLOOR DIVISION:",a//b)
print("EXPONENT:",a**b)
